name: Build Step

on:
    push:
        branches: [ main ]
#    pull_request:
#        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [20.19.0]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            # install dependencies
            - name: Check package.json and package-lock.json sync
              run: yarn install --dry-run
            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            # prisma
            - name: Generate Prisma Client
              run: npx prisma generate --schema=src/prisma/schema.prisma

            # build
            - name: Build app
              run: yarn build

    test-stage:
        runs-on: ubuntu-22.04
        needs: build
        steps:
          - name: "Setup Test later"
            uses: actions/checkout@v3
          - run: echo "Test stage"

    build-and-push-docker:
      needs: test-stage
      runs-on: ubuntu-22.04
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # push to main action
      steps:
        - uses: actions/checkout@v3

        - name: Create .env file
          run: |
            echo "PORT=8080" > .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env
            echo "AWS_CLOUDFRONT=${{ secrets.AWS_CLOUDFRONT }}" >> .env

          # Login to Docker Hub
        - name: Dockerhub login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract Git commit hash
          run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

          # Build and push docker images
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/fs-image:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/fs-image:${{ env.COMMIT_HASH }}
